---
title: "Analysis Part 2"
author: "Michèle, Lennart, Michel, Sebastian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library("tidyverse")
```

## load data
 
```{r}
df_normalized_combined <- readRDS("RDeeP_HeLa_Mitosis_normalized_combined.rds")
```

```{r}
dim(df_normalized_combined)
```

## global maxima for combined values

```{r}
d <- dim(df_normalized_combined)
rows <- d[1] 
columns <- d[2]
fractions_ctrl <- 25
fractions_RNase <- 25

df_global_maxima <- data.frame()
proteins <- rownames(df_normalized_combined)
fractionsnames <- colnames(df_normalized_combined)

for (z in 1:rows) {
  proteinname <- proteins[z]
  
  maxfc <- df_normalized_combined[z, 1]
  maxfcc <- 1
  
  for (fc in 2:25) {
    
    if (maxfc < df_normalized_combined[z, fc]) {
      maxfc <- df_normalized_combined[z, fc]
      maxfcc <- fc
    }
  }
  
  maxrna <- df_normalized_combined[z, 26]
  maxfcr <- 26
  
  for (fc in 27:50) {
    
    if (maxrna < df_normalized_combined[z, fc]) {
      maxrna <- df_normalized_combined[z, fc]
      maxfcr <- fc
    }
  }
  
  df_global_maxima <-
    rbind(
      df_global_maxima,
      data.frame(
        #global_maximum_ctrl_fraction1 = fractionsnames[maxfcc],
        ctrl_global_maximum_fraction = maxfcc,
        ctrl_global_maximum_value = maxfc,
        #global_maximum_rnase_fraction1 = fractionsnames[maxfcr],
        rnase_global_maximum_fraction = maxfcr - 25,
        rnase_global_maximum_value = maxrna
      )
    )
}

rownames(df_global_maxima) <- rownames(df_normalized_combined)
#View(df_global_maxima)
dim(df_global_maxima)
```

```{r}
# test whether both ways work the same, NOT IMPORTANT FOR REPORT
ctrl_global_maximum_fraction <- c()
ctrl_global_maximum_value <- c()
rnase_global_maximum_fraction <- c()
rnase_global_maximum_value <- c()

for (i in 1:nrow(df_normalized_combined)) {
  ctrl_global_maximum_value <-
    append(ctrl_global_maximum_value, max(df_normalized_combined[i, 1:25]))
  ctrl_global_maximum_fraction <-
    append(ctrl_global_maximum_fraction,
           which(df_normalized_combined[i, 1:25] == max(df_normalized_combined[i, 1:25])))
  rnase_global_maximum_value <-
    append(rnase_global_maximum_value, max(df_normalized_combined[i, 26:50]))
  rnase_global_maximum_fraction <-
    append(rnase_global_maximum_fraction,
           which(df_normalized_combined[i, 26:50] == max(df_normalized_combined[i, 26:50])))
  
}

df_global_maxima_test <-
  data.frame(
    row.names = rownames(df_normalized_combined),
    ctrl_global_maximum_fraction = ctrl_global_maximum_fraction,
    ctrl_global_maximum_value = ctrl_global_maximum_value,
    rnase_global_maximum_fraction = rnase_global_maximum_fraction,
    rnase_global_maximum_value = rnase_global_maximum_value
  )

sum(df_global_maxima != df_global_maxima_test)
```

```{r}
saveRDS(df_global_maxima, file = "RDeeP_HeLa_Mitosis_global_maxima.rds")
```

## global maxima for every replicate

In order to use the function above for every replicate, we need to split the data frame df_normalized into 6 data frames.

```{r}
df_normalized <- readRDS("RDeeP_HeLa_Mitosis_normalized.rds")

df_ctrl1 <- df_normalized[,grep("Ctrl_Rep1", colnames(df_normalized))]
df_ctrl2 <- df_normalized[,grep("Ctrl_Rep2", colnames(df_normalized))]
df_ctrl3 <- df_normalized[,grep("Ctrl_Rep3", colnames(df_normalized))]
df_rnase1 <- df_normalized[,grep("RNase_Rep1", colnames(df_normalized))]
df_rnase2 <- df_normalized[,grep("RNase_Rep2", colnames(df_normalized))]
df_rnase3 <- df_normalized[,grep("RNase_Rep3", colnames(df_normalized))]
```

```{r}
find_global_maxima <- function(df) {
  
  d <- dim(df)
  rows <- d[1]
  columns <- d[2]
  fractions_ctrl <- 25
  #fractions_RNase <- 25
  
  df_output <- data.frame()
  proteins <- rownames(df)
  fractionsnames <- colnames(df)
  
  for (z in 1:rows) {
    proteinname <- proteins[z]
    
    maxfc <- df[z, 1]
    maxfcc <- 1
    
    for (fc in 2:25) {
      if (maxfc < df[z, fc]) {
        maxfc <- df[z, fc]
        maxfcc <- fc
      }
    }
    
    #maxrna <- df[z, 26]
    #maxfcr <- 26
    
    #for (fc in 27:50) {
      #if (maxrna < df[z, fc]) {
        #maxrna <- df[z, fc]
        #maxfcr <- fc
      #}
    #}
    
    df_output <-
      rbind(
        df_output,
        data.frame(
          #global_maximum_ctrl_fraction1 = fractionsnames[maxfcc],
          ctrl_global_maximum_fraction = maxfcc,
          ctrl_global_maximum_value = maxfc
          #global_maximum_rnase_fraction1 = fractionsnames[maxfcr],
          #rnase_global_maximum_fraction = maxfcr - 25,
          #rnase_global_maximum_value = maxrna
        )
      )
  }
  
  rownames(df_output) <- rownames(df)
  #View(df_global_maxima)
  #dim(df_output)
  
  return(df_output)
}
```

```{r}
df_ctrl1_global_maxima <- find_global_maxima(df_ctrl1)
df_ctrl2_global_maxima <- find_global_maxima(df_ctrl2)
df_ctrl3_global_maxima <- find_global_maxima(df_ctrl3)
df_rnase1_global_maxima <- find_global_maxima(df_rnase1)
df_rnase2_global_maxima <- find_global_maxima(df_rnase2)
df_rnase3_global_maxima <- find_global_maxima(df_rnase3)

df_global_maxima_rep <-
  cbind(
    df_ctrl1_global_maxima,
    df_ctrl2_global_maxima,
    df_ctrl3_global_maxima,
    df_rnase1_global_maxima,
    df_rnase2_global_maxima,
    df_rnase3_global_maxima
  )
colnames(df_global_maxima_rep) <-
  c(
    "ctrl1_global_maximum_fraction",
    "ctrl1_global_maximum_value",
    "ctrl2_global_maximum_fraction",
    "ctrl2_global_maximum_value",
    "ctrl3_global_maximum_fraction",
    "ctrl3_global_maximum_value",
    "rnase1_global_maximum_fraction",
    "rnase1_global_maximum_value",
    "rnase2_global_maximum_fraction",
    "rnase2_global_maximum_value",
    "rnase3_global_maximum_fraction",
    "rnase3_global_maximum_value"
  )
```

```{r}
saveRDS(df_global_maxima_rep, file = "RDeeP_HeLa_Mitosis_global_maxima_rep.rds")
```

## local maxima 

```{r}
plot(1:25, df_normalized_combined[14, 1:25], type = "b")
plot(1:25, df_normalized_combined[2898, 1:25], type = "b")
plot(1:25, df_normalized_combined[2900, 1:25], type = "b")
plot(1:25, df_normalized_combined[2901, 1:25], type = "b")
```

### local maxima ctrl

```{r}
# create df that will contain the local maxima, because we do not know yet how many local maxima each protein will have we need to make space for more than one per protein and cut the rest of later

df_local_maxima_ctrl <-
  data.frame(
    row.names = rownames(df_normalized_combined),
    ctrl_local_maximum1_fraction = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum1_value = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum2_fraction = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum2_value = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum3_fraction = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum3_value = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum4_fraction = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum4_value = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum5_fraction = matrix(0, nrow(df_normalized_combined), 1),
    ctrl_local_maximum5_value = matrix(0, nrow(df_normalized_combined), 1)
  )
```

```{r}
for (i in 1:nrow(df_normalized_combined)) {
  # first loop iterating through the proteins
  over_4 <- c()
  # store indices of values over 4 for every protein in here (only temporary)
  
  for (j in 1:25) {
    # second loop iterating through all Ctrl fractions
    if (df_normalized_combined[i, j] > 4) {
      # only values > 4 are saved
      over_4 <- append(over_4, j)
    }
  }
  #print(over_4)
  local_maxima <- c()
  # store indices of values over 4 and with no higher neighbours (only temporary)
  
  for (v in over_4) {
    # iterate through all values that are > 4
    #print(df_normalized_combined[i, v])
    
    # values on boarders have to be treated differently
    
    # first value (no value to the left)
    if (v == 1) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 1:25])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # second value (only one value to the left)
    } else if (v == 2) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 1:25])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # 24th value (only one value to the right)
    } else if (v == 24) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 1:25])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # 25th value (no value to the right)
    } else if (v == 25) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 1:25])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # all other values to not have to be treated differently
    } else {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 1:25])) {
        local_maxima <- append(local_maxima, v)
      }
    }
  }
  #print(paste("protein", as.character(i)))
  #print(local_maxima)
  
  # now we need to save the protein name as well as the local maximum's position and value
  
  if (length(local_maxima) == 1) {
    # proteins with one local maximum
    
    df_local_maxima_ctrl[i, 1] <- local_maxima[1]
    df_local_maxima_ctrl[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    
  } else if (length(local_maxima) == 2) {
    # proteins with 2 local maxima
    
    df_local_maxima_ctrl[i, 1] <- local_maxima[1]
    df_local_maxima_ctrl[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_ctrl[i, 3] <- local_maxima[2]
    df_local_maxima_ctrl[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    
  } else if (length(local_maxima) == 3) {
    # proteins with 3 local maxima
    
    df_local_maxima_ctrl[i, 1] <- local_maxima[1]
    df_local_maxima_ctrl[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_ctrl[i, 3] <- local_maxima[2]
    df_local_maxima_ctrl[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_ctrl[i, 5] <- local_maxima[3]
    df_local_maxima_ctrl[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    
  } else if (length(local_maxima) == 4) {
    # proteins that have 4 local maxima
    
    df_local_maxima_ctrl[i, 1] <- local_maxima[1]
    df_local_maxima_ctrl[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_ctrl[i, 3] <- local_maxima[2]
    df_local_maxima_ctrl[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_ctrl[i, 5] <- local_maxima[3]
    df_local_maxima_ctrl[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    df_local_maxima_ctrl[i, 7] <- local_maxima[4]
    df_local_maxima_ctrl[i, 8] <-df_normalized_combined[i, local_maxima[4]]
    
  } else if (length(local_maxima) == 5) {
    # proteins with 5  local maxima
    
    df_local_maxima_ctrl[i, 1] <- local_maxima[1]
    df_local_maxima_ctrl[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_ctrl[i, 3] <- local_maxima[2]
    df_local_maxima_ctrl[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_ctrl[i, 5] <- local_maxima[3]
    df_local_maxima_ctrl[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    df_local_maxima_ctrl[i, 7] <- local_maxima[4]
    df_local_maxima_ctrl[i, 8] <-df_normalized_combined[i, local_maxima[4]]
    df_local_maxima_ctrl[i, 9] <- local_maxima[5]
    df_local_maxima_ctrl[i, 10] <-df_normalized_combined[i, local_maxima[5]]
    
  }
}
```

### local maxima rnase

```{r}
# create df that will contain the local maxima, because we do not know yet how many local maxima each protein will have we need to make space for more than one per protein and cut the rest of later

df_local_maxima_rnase <-
  data.frame(
    row.names = rownames(df_normalized_combined),
    rnase_local_maximum1_fraction = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum1_value = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum2_fraction = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum2_value = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum3_fraction = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum3_value = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum4_fraction = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum4_value = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum5_fraction = matrix(0, nrow(df_normalized_combined), 1),
    rnase_local_maximum5_value = matrix(0, nrow(df_normalized_combined), 1)
  )
```

```{r}
for (i in 1:nrow(df_normalized_combined)) {
  # first loop iterating through the proteins
  over_4 <- c()
  # store indices of values over 4 for every protein in here (only temporary)
  
  for (j in 26:50) {
    # second loop iterating through all Ctrl fractions
    if (df_normalized_combined[i, j] > 4) {
      # only values > 4 are saved
      over_4 <- append(over_4, j)
    }
  }
  #print(over_4)
  local_maxima <- c()
  # store indices of values over 4 and with no higher neighbours (only temporary)
  
  for (v in over_4) {
    # iterate through all values that are > 4
    #print(df_normalized_combined[i, v])
    
    # values on boarders have to be treated differently
    
    # 26th value (no value to the left)
    if (v == 26) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 26:50])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # 27th value (only one value to the left)
    } else if (v == 27) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 26:50])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # 49th value (only one value to the right)
    } else if (v == 49) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 26:50])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # 50th value (no value to the right)
    } else if (v == 50) {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 26:50])) {
        local_maxima <- append(local_maxima, v)
      }
      
      # all other values to not have to be treated differently
    } else {
      if (df_normalized_combined[i, v] > df_normalized_combined[i, v - 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v - 2] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 1] &
          df_normalized_combined[i, v] > df_normalized_combined[i, v + 2] &
          df_normalized_combined[i, v] != max(df_normalized_combined[i, 26:50])) {
        local_maxima <- append(local_maxima, v)
      }
    }
  }
  #print(paste("protein", as.character(i)))
  #print(local_maxima)
  
  # now we need to save the protein name as well as the local maximum's position and value
  
  if (length(local_maxima) == 1) {
    # proteins with one local maximum
    
    df_local_maxima_rnase[i, 1] <- local_maxima[1] - 25
    df_local_maxima_rnase[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    
  } else if (length(local_maxima) == 2) {
    # proteins with 2 local maxima
    
    df_local_maxima_rnase[i, 1] <- local_maxima[1] - 25
    df_local_maxima_rnase[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_rnase[i, 3] <- local_maxima[2] - 25
    df_local_maxima_rnase[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    
  } else if (length(local_maxima) == 3) {
    # proteins with 3 local maxima
    
    df_local_maxima_rnase[i, 1] <- local_maxima[1] - 25
    df_local_maxima_rnase[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_rnase[i, 3] <- local_maxima[2] - 25
    df_local_maxima_rnase[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_rnase[i, 5] <- local_maxima[3] - 25
    df_local_maxima_rnase[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    
  } else if (length(local_maxima) == 4) {
    # proteins that have 4 local maxima
    
    df_local_maxima_rnase[i, 1] <- local_maxima[1] - 25
    df_local_maxima_rnase[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_rnase[i, 3] <- local_maxima[2] - 25
    df_local_maxima_rnase[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_rnase[i, 5] <- local_maxima[3] - 25
    df_local_maxima_rnase[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    df_local_maxima_rnase[i, 7] <- local_maxima[4] - 25
    df_local_maxima_rnase[i, 8] <-df_normalized_combined[i, local_maxima[4]]
    
  } else if (length(local_maxima) == 5) {
    # proteins with 5  local maxima
    
    df_local_maxima_rnase[i, 1] <- local_maxima[1] - 25
    df_local_maxima_rnase[i, 2] <- df_normalized_combined[i, local_maxima[1]]
    df_local_maxima_rnase[i, 3] <- local_maxima[2] - 25
    df_local_maxima_rnase[i, 4] <-df_normalized_combined[i, local_maxima[2]]
    df_local_maxima_rnase[i, 5] <- local_maxima[3] - 25
    df_local_maxima_rnase[i, 6] <-df_normalized_combined[i, local_maxima[3]]
    df_local_maxima_rnase[i, 7] <- local_maxima[4] - 25
    df_local_maxima_rnase[i, 8] <-df_normalized_combined[i, local_maxima[4]]
    df_local_maxima_rnase[i, 9] <- local_maxima[5] - 25
    df_local_maxima_rnase[i, 10] <-df_normalized_combined[i, local_maxima[5]]
    
  }
}
```

### combine and save local maxima

```{r}
df_local_maxima <- as.data.frame(cbind(df_local_maxima_ctrl, df_local_maxima_rnase))
rownames(df_local_maxima) <- rownames(df_normalized_combined)
```

```{r}
saveRDS(df_local_maxima, file = "RDeeP_HeLa_Mitosis_local_maxima.rds")
```





