---
title: "Analysis Part 4"
author: "Michèle, Michel, Lennart, Sebastian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library("tidyverse")
library("uwot")
library("factoextra")
```

## Michel's Part

Load the normalized and combined data:
```{r}
df_normalized_combined <- readRDS("RDeeP_HeLa_Mitosis_normalized_combined.rds")
```

Perform pca and umap or only umap or only pca on data:
```{r}
# df_umap1: pca and umap
pca <- prcomp(df_normalized_combined)
df_umap1 <- as.data.frame(umap(pca$x))

# df_umap2 : only umap
df_umap2 <- as.data.frame(umap(df_normalized_combined))

# df_pca: only pca
df_pca <- as.data.frame(prcomp(df_normalized_combined)$x)
```

Plot both results to see wether they differ or not:
```{r}
ggplot(df_umap1, aes(x = V1, y = V2)) +
  geom_point()

ggplot(df_umap2, aes(x = V1, y = V2)) +
  geom_point()

ggplot(df_pca, aes(x = PC1, y = PC2)) +
  geom_point()
```

```{r}
n = 1
df_umap <- cbind(df_umap1, matrix(0, nrow(df_normalized_combined), 1))
colnames(df_umap) <- c("V1", "V2", "shift")

for (i in 1:nrow(df_umap)) {
  if (shift_global[i] < -n) {
    df_umap[i, 3] <- "left shift"
  } else if (shift_global[i] > n) {
    df_umap[i, 3] <- "right shift"
  } else {
    df_umap[i, 3] <- "no shift"
  }
}
```

```{r}
for (i in 1:nrow(df_umap)) {
  if (rownames(df_umap)[i] %in% rownames(df_rdeep)) {
    df_umap$rdeep[i] <- "rdeep"
  } else {
    df_umap$rdeep[i] <- "non rdeep"
  }
}
```

```{r}
ggplot(df_umap, aes(x = V1, y = V2, color = shift)) +
  geom_point()
```

```{r}
ggplot(df_umap, aes(x = V1, y = V2, color = rdeep)) +
  geom_point()
```

```{r}
x <- grep("left", df_umap$shift)
y <- grep("right", df_umap$shift)
z <- c(x, y)

df_umap_shift <- df_umap[z, ]
df_umap_no_shift <- df_umap[-z, ]

ggplot(df_umap_shift, aes(x = V1, y = V2, color = shift)) +
  geom_point()
ggplot(df_umap_no_shift, aes(x = V1, y = V2, color = shift)) +
  geom_point()
```

```{r}
n = 1
df_pca_shift <- cbind(df_pca, matrix(0, nrow(df_normalized_combined), 1))
colnames(df_pca_shift)[51] <- "shift"

for (i in 1:nrow(df_pca_shift)) {
  if (shift_global[i] < -n) {
    df_pca_shift[i, 51] <- "left shift"
  } else if (shift_global[i] > n) {
    df_pca_shift[i, 51] <- "right shift"
  } else {
    df_pca_shift[i, 51] <- "no shift"
  }
  
}
```

```{r}
ggplot(df_pca_shift, aes(x = PC1, y = PC2, color = shift)) +
  geom_point()
```


## Michel 2

```{r}
df_global_maxima <- readRDS("RDeeP_HeLa_Mitosis_global_maxima.rds")
```

```{r}
n = 1
df_global_maxima_shift <- cbind(df_global_maxima, matrix(0, nrow(df_normalized_combined), 1))
colnames(df_global_maxima_shift)[5] <- "shift"

for (i in 1:nrow(df_global_maxima_shift)) {
  if (shift_global[i] < -n) {
    df_global_maxima_shift[i, 5] <- "left shift"
  } else if (shift_global[i] > n) {
    df_global_maxima_shift[i, 5] <- "right shift"
  } else {
    df_global_maxima_shift[i, 5] <- "no shift"
  }
  
}
```

```{r}
ggplot(
  df_global_maxima_shift,
  aes(y = ctrl_global_maximum_fraction, x = rnase_global_maximum_fraction, color = shift)
) +
  geom_count()
```

```{r}
ggplot(
  df_global_maxima_shift,
  aes(y = ctrl_global_maximum_fraction, x = rnase_global_maximum_fraction, color = shift)
) +
  geom_jitter()
```

## Michèle's Part

```{r}
df_cluster <- as.data.frame(cbind(shift_global, pval_adjust_rep))
rownames(df_cluster) <- rownames(df_normalized)
```

```{r}
ggplot(df_cluster, aes(x = abs(shift_global), y = pval_adjust_rep)) +
  geom_point()
```

```{r}
wss = sapply(2:10, function(x) { 
  kmeans(df_normalized_combined, centers = x, nstart = 100)$tot.withinss
})
plot(2:10, wss, xlab = "numbers of centers", ylab = "total within-cluster sum of squares", type = "b")
```

```{r}
km <- kmeans(df_normalized_combined, centers = 3)

fviz_cluster(km, data = df_normalized_combined,
             #palette = c("#2E9FDF", "#00AFBB", "#E7B800"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
```




















